// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "remote-print.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



Example::Echo_ptr Example::Echo_Helper::_nil() {
  return ::Example::Echo::_nil();
}

::CORBA::Boolean Example::Echo_Helper::is_nil(::Example::Echo_ptr p) {
  return ::CORBA::is_nil(p);

}

void Example::Echo_Helper::release(::Example::Echo_ptr p) {
  ::CORBA::release(p);
}

void Example::Echo_Helper::marshalObjRef(::Example::Echo_ptr obj, cdrStream& s) {
  ::Example::Echo::_marshalObjRef(obj, s);
}

Example::Echo_ptr Example::Echo_Helper::unmarshalObjRef(cdrStream& s) {
  return ::Example::Echo::_unmarshalObjRef(s);
}

void Example::Echo_Helper::duplicate(::Example::Echo_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

Example::Echo_ptr
Example::Echo::_duplicate(::Example::Echo_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

Example::Echo_ptr
Example::Echo::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


Example::Echo_ptr
Example::Echo::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

Example::Echo_ptr
Example::Echo::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Echo _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Echo* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Echo;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* Example::Echo::_PD_repoId = "IDL:Example/Echo:1.0";


Example::_objref_Echo::~_objref_Echo() {
  
}


Example::_objref_Echo::_objref_Echo(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::Example::Echo::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
Example::_objref_Echo::_ptrToObjRef(const char* id)
{
  if (id == ::Example::Echo::_PD_repoId)
    return (::Example::Echo_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::Example::Echo::_PD_repoId))
    return (::Example::Echo_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for Example::Echo::echoChar

// Proxy call descriptor class. Mangled signature:
//  _cstring_i_cunsigned_plong
class _0RL_cd_1f03eabd1a63181c_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_1f03eabd1a63181c_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::ULong arg_0;
  ::CORBA::String_var result;
};

void _0RL_cd_1f03eabd1a63181c_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_1f03eabd1a63181c_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::ULong&)arg_0 <<= _n;

}

void _0RL_cd_1f03eabd1a63181c_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_1f03eabd1a63181c_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_1f03eabd1a63181c_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_1f03eabd1a63181c_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_1f03eabd1a63181c_00000000* tcd = (_0RL_cd_1f03eabd1a63181c_00000000*)cd;
  Example::_impl_Echo* impl = (Example::_impl_Echo*) svnt->_ptrToInterface(Example::Echo::_PD_repoId);
  tcd->result = impl->echoChar(tcd->arg_0);


}

char* Example::_objref_Echo::echoChar(::CORBA::ULong mesg)
{
  _0RL_cd_1f03eabd1a63181c_00000000 _call_desc(_0RL_lcfn_1f03eabd1a63181c_10000000, "echoChar", 9);
  _call_desc.arg_0 = mesg;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

Example::_pof_Echo::~_pof_Echo() {}


omniObjRef*
Example::_pof_Echo::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::Example::_objref_Echo(ior, id);
}


::CORBA::Boolean
Example::_pof_Echo::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::Example::Echo::_PD_repoId))
    return 1;
  
  return 0;
}

const Example::_pof_Echo _the_pof_Example_mEcho;

Example::_impl_Echo::~_impl_Echo() {}


::CORBA::Boolean
Example::_impl_Echo::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "echoChar")) {

    _0RL_cd_1f03eabd1a63181c_00000000 _call_desc(_0RL_lcfn_1f03eabd1a63181c_10000000, "echoChar", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
Example::_impl_Echo::_ptrToInterface(const char* id)
{
  if (id == ::Example::Echo::_PD_repoId)
    return (::Example::_impl_Echo*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::Example::Echo::_PD_repoId))
    return (::Example::_impl_Echo*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
Example::_impl_Echo::_mostDerivedRepoId()
{
  return ::Example::Echo::_PD_repoId;
}

POA_Example::Echo::~Echo() {}

